"""Tone / Constructiveness Evaluator — LLM-as-a-Judge for intervention messages.

Binary classifier that gates conflict-resolution nudges before delivery.
Classifies each draft intervention message as CONSTRUCTIVE or PUNITIVE
using a single-criterion evaluation at near-zero temperature.

Uses HIGH-TIER LLM (llama-3.3-70b-versatile via ``get_high_tier_llm()``)
at temperature=0.0 for deterministic classification.
"""

from __future__ import annotations

import json
import logging
import re
from typing import Any

from llm import get_high_tier_llm
from state.schema import SyncUpState, ToneResult

logger = logging.getLogger(__name__)

MAX_RETRIES: int = 2  # 3 total attempts


# ---------------------------------------------------------------------------
# Prompt templates
# ---------------------------------------------------------------------------

SYSTEM_PROMPT: str = """\
You are evaluating a message that will be sent to a student who is \
falling behind on a group project. Classify this message as either \
CONSTRUCTIVE or PUNITIVE.

A CONSTRUCTIVE message: identifies the issue factually, asks about \
roadblocks, offers help, proposes a concrete next step, maintains \
a supportive tone.

A PUNITIVE message: uses blame language, guilt tactics, passive-aggressive \
phrasing, threats, or implies the student is lazy/irresponsible.

You MUST respond with ONLY a JSON object — no markdown fences, no \
explanation, no text before or after the JSON:
{
  "classification": "constructive" or "punitive",
  "reasoning": "one sentence explaining your judgment",
  "flagged_phrases": ["list of problematic phrases, empty if constructive"]
}

Use near-zero temperature. Be deterministic. If the message is \
supportive and solution-oriented, return classification="constructive".
"""


# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------


def _extract_json(raw: str) -> str:
    """Strip markdown code fences and preamble text to isolate JSON.

    Args:
        raw: Raw LLM response text.

    Returns:
        A cleaned string that should be valid JSON.

    Raises:
        ValueError: If no JSON object can be located in the response.
    """
    text = raw.strip()
    fence_pattern = re.compile(r"```(?:json)?\s*\n?(.*?)\n?\s*```", re.DOTALL)
    match = fence_pattern.search(text)
    if match:
        return match.group(1).strip()
    brace_idx = text.find("{")
    if brace_idx == -1:
        raise ValueError("No JSON object found in LLM response")
    return text[brace_idx:]


def _parse_response(raw: str) -> ToneResult:
    """Parse raw LLM text into a validated ``ToneResult``.

    Args:
        raw: Raw LLM response content string.

    Returns:
        A validated ``ToneResult`` instance.

    Raises:
        json.JSONDecodeError: If the extracted text is not valid JSON.
        ValueError: If Pydantic validation fails or no JSON found.
    """
    cleaned = _extract_json(raw)
    data = json.loads(cleaned)
    return ToneResult.model_validate(data)


def _build_user_prompt(message: str) -> str:
    """Build the user message for tone evaluation.

    Wraps the intervention message in untrusted data delimiters since
    the message was generated by another LLM call.

    Args:
        message: The draft intervention message to evaluate.

    Returns:
        The formatted user prompt string.
    """
    return (
        "Evaluate the following intervention message:\n\n"
        f"<<<UNTRUSTED_DATA_START>>>\n{message}\n<<<UNTRUSTED_DATA_END>>>\n\n"
        "Respond with ONLY the JSON object."
    )


# ---------------------------------------------------------------------------
# Evaluator node
# ---------------------------------------------------------------------------


def tone_evaluator(state: SyncUpState) -> dict[str, Any]:
    """Tone / Constructiveness Evaluator node.

    Classifies the draft intervention message as CONSTRUCTIVE or PUNITIVE.
    If punitive, increments the rewrite counter so the graph routes back
    to conflict_resolution for a rewrite.

    Args:
        state: The current ``SyncUpState``.

    Returns:
        A dict with ``tone_result`` (ToneResult) and optionally
        ``tone_rewrite_count`` (int) to be merged into state.
    """
    if state.draft_intervention is None:
        return {"tone_result": None}

    llm = get_high_tier_llm(temperature=0.0)
    user_msg = _build_user_prompt(state.draft_intervention.message)

    last_error: Exception | None = None

    for attempt in range(MAX_RETRIES + 1):
        try:
            response = llm.invoke(
                [
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": user_msg},
                ]
            )
            result = _parse_response(response.content)

            if result.classification == "punitive":
                logger.info(
                    "Draft intervention flagged as punitive: %s",
                    result.reasoning,
                )
                return {
                    "tone_result": result,
                    "tone_rewrite_count": state.tone_rewrite_count + 1,
                }

            return {"tone_result": result}

        except (json.JSONDecodeError, ValueError, KeyError) as exc:
            last_error = exc
            logger.warning(
                "Tone evaluation attempt %d/%d failed: %s",
                attempt + 1,
                MAX_RETRIES + 1,
                exc,
            )

    # All retries exhausted — default to constructive to avoid blocking delivery
    logger.error(
        "Tone evaluation failed after %d attempts: %s — defaulting to constructive",
        MAX_RETRIES + 1,
        last_error,
    )
    return {
        "tone_result": ToneResult(
            classification="constructive",
            reasoning="Tone evaluation failed — defaulting to constructive",
        ),
    }
